title: Alauda DevOps Artifact Hub Shim Docs
logoText: Alauda DevOps Artifact Hub Shim Docs
lang: en
root: docs

api:
  crds:
    - docs/shared/crds/**/*.{yaml,yml}
  openapis:
    - docs/shared/openapis/**/*.{json,yaml,yml}

permission:
  functionresources:
    - docs/shared/functionresources/**/*.{yaml,yml}
  roletemplates:
    - docs/shared/roletemplates/**/*.{yaml,yml}

internalRoutes:
  - '*/development/**/*'
  - '**/development/**/*'
  - '*/design/**/*'
  - '**/design/**/*'

releaseNotes:
  queryTemplates:
    unfixed: |
      project = <%= project %> AND affectedVersion in ("artifacthub-shim-<%= version %>") AND type = Bug AND status in (Cancelled) AND ReleaseNotesStatus = Publish
    fixed: |
      project = <%= project %> AND fixVersion in ("artifacthub-shim-<%= version %>") AND type = Bug AND status in (Done, Resolved) AND ReleaseNotesStatus = Publish
